schedule:
  hotwater_schedule:
    name: "Hotwater schedule"
    monday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    tuesday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    wednesday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    thursday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    friday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    saturday:
      - from: "7:00:00"
        to: "09:30:00"
      - from: "17:00:00"
        to: "21:30:00"
    sunday:
      - from: "8:00:00"
        to: "10:00:00"
      - from: "17:00:00"
        to: "21:30:00"
